class ConnectionSQL{
  static const CREATE_DATABASE = '''
  CREATE TABLE `TB_CLIENTE`(
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT, 
    `NOME` TEXT NOT NULL, 
    `CPF` TEXT NOT NULL, 
    `TELEFONE` TEXT NOT NULL, 
    `ENDERECO` TEXT NOT NULL,
    `BAIRRO` TEXT NOT NULL,
    `CEP` TEXT NOT NULL,
  );
  
  CREATE TABLE `TB_PRODUTO`(
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT, 
    `NOME` TEXT NOT NULL, 
    `PRECO` REAL NOT NULL, 
    `QUANTIDADE` INTEGER NOT NULL, 
    `DESCRICAO` TEXT NOT NULL,
  );
  
 CREATE TABLE `TB_FORNECEDOR`(
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT, 
    `NOME` TEXT NOT NULL, 
    `CNPJ` TEXT NOT NULL, 
    `TELEFONE` TEXT NOT NULL, 
    `ENDERECO` TEXT NOT NULL,
    `BAIRRO` TEXT NOT NULL,
    `CEP` TEXT NOT NULL,
  );  
  ''';
}